CREATE TABLE EMPLOYEE(
    eid INTEGER,
    name VARCHAR(20) NOT NULL,
    salary INTEGER,
    status VARCHAR(20),
    supereid INTEGER NOT NULL,
    PRIMARY KEY (eid));

CREATE TABLE DEPENDENT
    (name VARCHAR(20),
    eid INTEGER NOT NULL,
    sex VARCHAR(20),
    relationship VARCHAR(20),
    PRIMARY KEY (name, eid),
    FOREIGN KEY (eid) REFERENCES EMPLOYEE ON DELETE CASCADE);

CREATE TABLE PROJECT
    (pid INTEGER,
    budget INTEGER,
    PRIMARY KEY (pid)
    );

CREATE TABLE DEPARTMENT
    (did INTEGER,
    PRIMARY KEY (did)
    );

-- COMBINE WORKS AND EMPLOYED INTO EMPLOYEE?? nvm 
CREATE TABLE Works
    (pid INTEGER,
    eid INTEGER,
    start_date DATE,
    hours INTEGER,
    PRIMARY KEY (pid, eid),
    FOREIGN KEY (pid) REFERENCES PROJECT ON DELETE CASCADE,
    FOREIGN KEY (eid) REFERENCES EMPLOYEE ON DELETE CASCADE
    );

CREATE TABLE Assigned
    (pid INTEGER,
    did INTEGER,
    PRIMARY KEY (pid, did),
    FOREIGN KEY (pid) REFERENCES PROJECT ON DELETE CASCADE,
    FOREIGN KEY (did) REFERENCES DEPARTMENT ON DELETE CASCADE
    );

CREATE TABLE Employed
    (eid INTEGER,
    did INTEGER,
    start_date DATE,
    PRIMARY KEY (eid, did),
    FOREIGN KEY (eid) REFERENCES EMPLOYEE ON DELETE CASCADE,
    FOREIGN KEY (did) REFERENCES DEPARTMENT ON DELETE CASCADE
    );


